name: 多时段安全提醒

on:
  schedule:
    # 北京时间 0:06 (UTC时间 16:06)
    - cron: '09 16 * * *'
    
    # 北京时间 7:00 (UTC时间 23:00)
    #- cron: '0 23 * * *'
    
    # 北京时间 22:00 (UTC时间 14:00)
    #- cron: '0 14 * * *'
    
    # 北京时间 23:00 (UTC时间 15:00)
    #- cron: '0 15 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: pip install requests
      
    - name: 发送安全提醒
      env:
        DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
        DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
      run: python safety_reminder.py
      
    - name: 记录执行时间
      run: |
        echo "执行时间(北京时间): $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
        echo "对应UTC时间: $(date -u +'%Y-%m-%d %H:%M:%S')"
        echo "触发时间点: ${{ github.event.schedule }}"
